-- Ensure RLS is disabled on all tables
ALTER TABLE IF EXISTS stakers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS rewards DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS platform_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS webhook_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS admin_actions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS withdrawal_locks DISABLE ROW LEVEL SECURITY;
